# Generated by Django 4.2.11 on 2024-09-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network_assignment', '0003_remove_comment_commented_by_comment_commented_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
